import { useEffect, useRef, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { Html5QrcodeScanner } from 'html5-qrcode';
import { Camera, X, RefreshCw, AlertCircle } from 'lucide-react';
import { Button } from '../components/ui/button';
import { toast } from 'sonner';

const ScannerPage = () => {
    const navigate = useNavigate();
    const [isScanning, setIsScanning] = useState(true);
    const scannerRef = useRef<Html5QrcodeScanner | null>(null);

    useEffect(() => {
        // Initialize scanner
        const scanner = new Html5QrcodeScanner(
            "reader",
            {
                fps: 10,
                qrbox: { width: 250, height: 250 },
                aspectRatio: 1.0,
                showTorchButtonIfSupported: true,
                showZoomSliderIfSupported: true,
            },
            /* verbose= */ false
        );

        scanner.render(onScanSuccess, onScanFailure);
        scannerRef.current = scanner;

        return () => {
            if (scannerRef.current) {
                scannerRef.current.clear().catch(_error => {
                    console.error("Failed to clear scanner", _error);
                });
            }
        };
    }, []);

    const onScanSuccess = (decodedText: string) => {
        // Stop scanning
        if (scannerRef.current) {
            scannerRef.current.pause(true);
        }
        setIsScanning(false);

        // Typical QR value generated by qrUtils: http://domain/products/id
        // We want to extract the ID or just use the local part if it's our domain
        try {
            const url = new URL(decodedText);
            const pathParts = url.pathname.split('/');
            const productId = pathParts[pathParts.length - 1];

            if (productId && decodedText.includes('/products/')) {
                toast.success('Producto detectado');
                navigate(`/products/${productId}`);
            } else {
                toast.error('Código QR no reconocido como producto de StockPro');
                if (scannerRef.current) scannerRef.current.resume();
                setIsScanning(true);
            }
        } catch (e) {
            // Not a URL, maybe it's just the ID?
            if (decodedText.length > 20) { // Assume it's a GUID/ID
                navigate(`/products/${decodedText}`);
            } else {
                toast.error('Contenido de QR no válido');
                if (scannerRef.current) scannerRef.current.resume();
                setIsScanning(true);
            }
        }
    };

    const onScanFailure = (error: any) => {
        // Standard scanner failure (no QR in frame) - we don't notify user here
    };

    return (
        <div className="max-w-xl mx-auto px-4 py-8 flex flex-col items-center">
            <div className="w-full bg-white rounded-2xl p-6 shadow-sm border border-gray-100 text-center space-y-6">
                <div className="flex justify-between items-center">
                    <h1 className="text-2xl font-bold text-gray-900 flex items-center gap-2">
                        <Camera className="h-6 w-6 text-blue-600" />
                        Escanear Código QR
                    </h1>
                    <button onClick={() => navigate(-1)} className="p-2 hover:bg-gray-100 rounded-full">
                        <X className="h-6 w-6 text-gray-500" />
                    </button>
                </div>

                <div className="relative aspect-square w-full rounded-2xl overflow-hidden bg-gray-900 flex items-center justify-center">
                    <div id="reader" className="w-full h-full"></div>
                    {!isScanning && (
                        <div className="absolute inset-0 bg-black/60 flex flex-col items-center justify-center text-white p-6">
                            <RefreshCw className="h-12 w-12 mb-4 animate-spin-slow" />
                            <p className="text-lg font-medium">Procesando código...</p>
                        </div>
                    )}
                </div>

                <div className="text-sm text-gray-500 bg-blue-50 p-4 rounded-xl flex gap-3 text-left">
                    <AlertCircle className="h-5 w-5 text-blue-600 flex-shrink-0" />
                    <p>Encuadra el código QR del producto dentro del recuadro para visualizar su información automáticamente.</p>
                </div>

                <Button
                    variant="outline"
                    className="w-full py-6 rounded-xl font-bold"
                    onClick={() => navigate('/products')}
                >
                    Volver al Inventario
                </Button>
            </div>
        </div>
    );
};

export default ScannerPage;
